train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./data
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 1500
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./del
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: ow-slr
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    starting_window_size: 5
    ending_window_size: 3
    hidden_size: 64
    lr_height_width: 48
    semiLocal_length: 6
    distance_decay_rate: 0.25
    decoder_layers: [128, 128, 128, 128]
    kernel_size: 3
    # num_epochs: 100

optimizer:
  name: adam
  # args:
  lr: 1.e-4
epochs: 100
multi_step_lr:
  milestones: [40, 60, 70]
  gamma: 0.3

save: "save/"
save_every: 10


